In [1]:
import numpy as np

In [5]:
urn = ['blue', 'blue', 'blue', 'black', 'black']
print('Sample 1:', np.random.choice(urn, size=2, replace=False))
print('Sample 2:', np.random.choice(urn, size=2, replace=False))

Sample 1: ['black' 'blue']
Sample 2: ['blue' 'blue']

In [6]:
n = 10_000
samples = [np.random.choice(urn, size=2, replace=False) for _ in range(n)]
is_matching = [marble1 == marble2 for marble1, marble2 in samples]
print(f"Proportion of samples with matching marbles: {np.mean(is_matching)}")

Proportion of samples with matching marbles: 0.4068

## 3.1.1 표본 추출 설계

In [7]:
from itertools import combinations

In [9]:
all_samples = ["".join(sample) for sample in combinations("ABCDEFG", 3)]
print(all_samples)
print("Number of Samples:", len(all_samples))

['ABC', 'ABD', 'ABE', 'ABF', 'ABG', 'ACD', 'ACE', 'ACF', 'ACG', 'ADE', 'ADF', 'ADG', 'AEF', 'AEG', 'AFG', 'BCD', 'BCE', 'BCF', 'BCG', 'BDE', 'BDF', 'BDG', 'BEF', 'BEG', 'BFG', 'CDE', 'CDF', 'CDG', 'CEF', 'CEG', 'CFG', 'DEF', 'DEG', 'DFG', 'EFG']
Number of Samples: 35

In [12]:
from itertools import permutations
print(["".join(sample) for sample in permutations("ABC")])

['ABC', 'ACB', 'BAC', 'BCA', 'CAB', 'CBA']

## 3.1.2. 표본의 통계 분포

## 3.1.3. 표본 분포 시뮬레이션

In [13]:
urn = [1, 1, 0, 1, 0, 1, 0]

In [14]:
sample = np.random.choice(urn, size=3, replace=False)
print(f"Sample: {sample}")
print(f"Prop Failures: {sample.mean()}")

Sample: [1 0 0]
Prop Failures: 0.3333333333333333

In [15]:
samples = [np.random.choice(urn, size=3, replace=False) for _ in range(10_000)]
prop_failures = [s.mean() for s in samples]

In [17]:
import pandas as pd

In [18]:
unique_els, counts_els = np.unique(prop_failures, return_counts=True)
pd.DataFrame({
    "Proportion of failures": unique_els,
    "Fraction of Samples": counts_els / 10_000,
})

   Proportion of failures  Fraction of Samples
0                0.000000               0.0294
1                0.333333               0.3468
2                0.666667               0.5142
3                1.000000               0.1096

## 3.1.4. 초기하분포 시뮬레이션

In [19]:
simulations_fast = np.random.hypergeometric(
    ngood=4, nbad=3, nsample=3, size=10_000
)
print(simulations_fast)

[1 1 1 ... 2 1 1]

In [20]:
unique_els, counts_els = np.unique(simulations_fast, return_counts=True)
pd.DataFrame({
    "Number of failures": unique_els,
    "Fraction of samples": counts_els / 10_000,
})

   Number of failures  Fraction of samples
0                   0               0.0288
1                   1               0.3489
2                   2               0.5058
3                   3               0.1165